import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import sharp from "sharp";
import { loadDataModule, loadProjects } from "./load-projects.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const output = resolve(
  root,
  process.env.NEXT_OUTPUT_DIR ?? ".next",
  "server/app",
);
const catalog = loadDataModule("app/portfolio/web-studies/catalog.ts");
const projects = loadProjects();
const existing = [
  "noelle",
  "nella",
  "cortex",
  "band-of-agents",
  "content-pipeline",
  "forge",
  "archgraph",
  "omegahack",
  "localhost-mirror",
  "lumen-frontier",
  "grit-x-awa",
  "study-hub",
  "valhalla",
  "redline",
  "lumen",
  "portpeek",
  "construcredit",
  "agentbar",
  "alfred",
  "anki",
];
const websites = projects.filter((project) =>
  catalog.isWebsiteStudy(project.slug),
);
const htmlFor = (path) =>
  readFileSync(resolve(output, `${path.slice(1)}.html`), "utf8").replace(
    /<script\b[^>]*>[^]*?<\/script>/gi,
    "",
  );

test("The website catalog adds twenty-four unique projects and retains the existing twenty", () => {
  assert.equal(websites.length, 24);
  assert.equal(new Set(projects.map((project) => project.slug)).size, 44);
  assert.deepEqual(
    projects.slice(0, existing.length).map((project) => project.slug),
    existing,
  );
  assert.equal(new Set(websites.map((project) => project.num)).size, 24);
  assert.equal(
    new Set(catalog.websiteRecords.map((record) => record.challenge)).size,
    24,
  );
  const titles = catalog.websiteRecords.flatMap((record) =>
    record.decisions.map(([title]) => title),
  );
  assert.equal(new Set(titles).size, titles.length);
  assert.equal(
    websites.filter((project) => project.slug.endsWith("-original")).length,
    4,
  );
});

for (const project of websites) {
  test(`${project.slug}: live site, brand kit and the shared repository are explicit`, () => {
    const base = `https://pablomanjarres.github.io/twenty-web-studies/${project.slug}/`;
    assert.equal(project.links.find((link) => link.kind === "live")?.url, base);
    assert.equal(
      project.links.find((link) => link.label === "Brand kit")?.url,
      `${base}brand/`,
    );
    assert.equal(
      project.links.find((link) => link.kind === "repo")?.url,
      "https://github.com/pablomanjarres/twenty-web-studies",
    );
    const story = catalog.getWebsiteCaseStudy(project.slug);
    assert.equal(story.platform, "Responsive website");
    assert.equal(story.challenge, project.problem);
    assert.equal(story.decisions.length, 3);
    assert.ok(
      !/https?:\/\/|[\w.+-]+@[\w.-]+\.[a-z]{2,}|generated by/i.test(
        JSON.stringify(story),
      ),
    );
    if (project.slug.endsWith("-original"))
      assert.ok(project.title.endsWith(" · Original"));
  });

  test(`${project.slug}: declared media dimensions match the actual delivered images`, async () => {
    const media = catalog.getWebsiteMedia(project.slug);
    assert.equal(media.length, 4);
    for (const asset of media) {
      const file = resolve(root, "public", asset.src.slice(1));
      assert.ok(existsSync(file), `Missing ${asset.src}`);
      const image = await sharp(file).metadata();
      assert.equal(image.width, asset.width);
      assert.equal(image.height, asset.height);
      assert.ok(asset.alt.includes(project.title));
    }
    assert.equal(media[0].kind, "presentation");
    assert.ok(media[2].height > media[2].width);
    assert.equal(media[3].kind, "presentation");
    assert.equal(
      catalog.getWebsiteInterfaceViews(project.slug)[0].asset.kind,
      "screen",
    );
  });

  test(`${project.slug}: its case study is rendered and linked from the visible website grid`, () => {
    const archive = htmlFor("/portfolio");
    const section = archive.match(
      /<section\b[^>]*aria-labelledby="websites-heading"[^>]*>([^]*?)<\/section>/,
    )?.[1];
    assert.ok(section, "Missing website studies section");
    assert.match(section, new RegExp(`data-project="${project.slug}"`));
    const html = htmlFor(`/portfolio/projects/${project.slug}`);
    for (const link of project.links)
      assert.ok(html.includes(`href="${link.url}"`));
    assert.ok(html.includes('aria-labelledby="workbench-interfaces"'));
    assert.ok(html.includes(project.cover));
    assert.ok(
      html.includes(
        encodeURIComponent(`/portfolio/web-studies/${project.slug}/mobile.webp`),
      ),
    );
    assert.ok(
      html.includes(
        encodeURIComponent(`/portfolio/web-studies/${project.slug}/product.webp`),
      ),
    );
  });
}
